### ISSUE TITLE
TODO-list (self reminder)

### ISSUE THREAD

**Issue by inobelar** [inobelar/taffy_cpp#1]
- [x] ~~Find all 'Self' in rust code & make same in C++~~

- [x] ~~'Default' trait implementation must contain 'static default' method~~

- [ ] Describe `Default`, `Debug` and `Display` traits (used in DebugLogger.hpp for example)

- [ ] Implement the next attributes:
  - `#[inline]`  --> force inline pragma
  - `#[must_use]` --> [[nodiscard]]
  - `#[track_caller]` --> ???

- [ ] Implement Iterator<Item> trait **better**
    - Fix 'Duplicates'! (well,  simply grep for it 'DUPLICATE')

- [ ] Check all `Option::unwrap()` -> it must be really `unwrap()'` not simple `.value()`
  - Same for `?` shortcut
  - `.unwrap_or()`
  - `.unwrap_or_else()`
    - Same for 'tests'
    - For this we must tweak `Some` deduction, that currently ... broken

- [ ] Check, where C++ lambda can be 'static' and make it!

- [ ] Each `Some` AND `None` in C++ must be same as in Rust, not `Option<T>{...}` and `Option<T>{}`
    - Same for 'tests'

- [ ] TODO: use newly added 'Ordering' where it's needed

- [ ] TODO: sys for allocator-less environment (non Vec<T>)

- [ ] Implement the next test somehow: taffy/tests/serde.rs

- [ ] Replace `std::function` usage everywhere, with something lightweight

- [ ] Somehow resolve third-party libraries distribution:
  - It must not require adding extra 'include pathes' to make `taffy_cpp` work
  - Maybe we need only distribute libs used-sources (lilke doctest in tests), instead the whole sub-project ?
  
 - [ ] amalgamation
 
 - [ ] WTF in `Release` with `Style`::`aspect_ratio` & `justify_content` - warnings about 'possibly unitialized'
